### ISSUE TITLE
Why does Display( IdentityMorphism( SubobjectClassifier( Quivers ) ) ) ) speed up a subsequent computations?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/FunctorCategories#88]
The compiler is currently unable to reach this speedup, although it should.

**Comment by zickgraf** [comment]
Does `Display( IdentityMorphism( SubobjectClassifier( quivers ) ) ) )` also speed up the computation when using the compiled code?

**Comment by mohamed-barakat** [comment]
No :(

**Comment by mohamed-barakat** [comment]
after executing `gap examples/CategoryOfQuivers.g`:

```gap
gap> Display( IdentityMorphism( SubobjectClassifier( Quivers ) ) );
...
gap> ListOfSubobjects( SubobjectClassifier( Quivers ) );
...
gap> Length( last );
39
gap> time;
21643
```

**Comment by zickgraf** [comment]
> Why does Display( IdentityMorphism( SubobjectClassifier( Quivers ) ) ) ) speed up a subsequent computations?

As expected, this is due to caching. When using
```
##
AddIsEqualForCacheForMorphisms( SkeletalFinSets,
  function ( cat, mor1, mor2 )
    
    return IsEqualForMorphismsOnMor( cat, mor1, mor2 );
    
end );
```
the example is fast even without calling `Display( ... )` before. The call to `Display` evaluates a natural transformation and populates some cache. The cache makes some subsequent operations return identical objects/morphisms, which allow the caching in SkeletalFinSets to kick in.
This is a bit unexpected at first, because it should not matter if we populate the cache before the computation or not, except if garbage collection plays a role. However, I have reduced this to an example where it makes a difference if I keep a reference to a variable or not. So the results of the computations in the call to `Display` seem to not be garbage collected. I guess this is due to the complicated setup of functors and natural transformations in CAP.

> The compiler is currently unable to reach this speedup, although it should.

The example does currently not work on the `functional` or `lazy` branches, so I could not reproduce this. My guess is that the compiler actually deduplicates this but does not produce an optimal result in general, making it slower again. If you have a running example using compiled code, we can try to test this hypothesis by taking a sublist in `ListOfSubobjects`: If the runtime does not scale with the length of the sublist, the compiler has actually deduplicated everything possible and the problem is somewhere else.

**Comment by zickgraf** [comment]
Addendum: `SetDefaultCachingCrisp( );` also makes the code fast. Setting only `SkeletalFinSets` to crisp caching does not help.

**Comment by mohamed-barakat** [comment]
Thank you so much for the analysis.

**Comment by zickgraf** [comment]
> The compiler is currently unable to reach this speedup, although it should.

According to our discussion yesterday, the compiler is now able to reach this speedup and we can close this issue, correct?

**Comment by mohamed-barakat** [comment]
Correct.

**Comment by mohamed-barakat** [comment]
Thank you very much.
